# https://docs.docker.com/ci-cd/github-actions/
name: Docker Hub Publishing

on:
  workflow_dispatch:
    inputs:
      swiftformat-version:
        description: SwiftFormat version
        required: true
      docker-publish:
        description: Publish to Docker Hub
        default: "false"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Resolve tags
        id: resolve-tags
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/swiftformat
          VERSION=${{ github.event.inputs.swiftformat-version }}
          LATEST_VERSION=$(
            curl --silent \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/nicklockwood/SwiftFormat/releases/latest |
              jq -r .tag_name
          )
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $LATEST_VERSION == $VERSION ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: |
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            swift_format_version=${{ github.event.inputs.swiftformat-version }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event.inputs.docker-publish == 'true' }}
          tags: ${{ steps.resolve-tags.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
